name: recoverylab_front
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

  cupertino_icons: ^1.0.8
  sizer: ^3.1.3
  google_fonts: ^6.3.1
  font_awesome_flutter: ^10.7.0
  dotted_line: ^3.0.0
  image_picker: ^1.1.2
  flutter_launcher_icons: ^0.14.4
  http: ^1.6.0
  flutter_riverpod: ^3.2.0
  flutter_secure_storage: ^10.0.0
  solar_icons: ^0.0.5
  curved_navigation_bar: ^1.0.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/
